

spring:
  datasource:
    username: root
    password: x
    url: jdbc:mysql://39.108.1.211:3306/sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: redis
  redis:
    host: r-xcs.com
    password: x
    lettuce:
      pool:
        max-active: 16
        max-wait: 10ms