

#spring:
#  datasource:
#    url: jdbc:mysql://39.108.1.211:3307/sharding_db?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
#    username: root
#    password: Yang123456!qazwsx
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      minimum-idle: 20
#      maximum-pool-size: 100
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: MyHikariCP
#      max-lifetime: 30000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.example.demo.dao
  global-config:
    id-type: 1
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

